version: "3"

services:
  ################################
  mongodb:
     build: ./db
    container_name: "mongodb"
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: firstdb
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
  ################################
  web:
    container_name: web_api_rest
    build: ./web
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
